from .complaint import Complaint
from .case import Case
from .officer import Officer
from .evidence import Evidence
from .document import Document
from .case_diary import CaseDiary
from .suspect import Suspects
from .victim import Victim
from .witness import Witness
from .medical_report import MedicalReport
from .remand_detail import RemandDetail
from .court_custody import CourtCustody
from .case_legal_sections import CaseLegalSection
from .legal_sections import LegalSection
from .legal_section_mappings import LegalSectionMapping
from .recommendations import Recommendation
from .fir_drafts import FirDraft
from .landmarks import Landmark
